### ISSUE TITLE
Toutes classe doivent avoir une méthode main pour des tests

### ISSUE THREAD

**Issue by SergeSULABOSIO** [e-study/eStudy_NetBeans#5]
Comme l'indique le titre du issue,
Vous devez ajouter à chaque classe une méthode main permettant d'effectuer des tests d'exécution.

Exemple:
`public static void main(String[] args){
      System.out.println("Hello");
}`

Merci.

**Comment by elvicc** [comment]
Je veux travailler sur la classe Horaire.

From Victor

**Comment by wins95** [comment]
je travaille sur la classe Enseignant

**Comment by 003francis** [comment]
Moi, je vais travailler sur Faculté et Etablissement!

**Comment by 003francis** [comment]
> Comme l'indique le titre du issue,
> Vous devez ajouter à chaque classe une méthode main permettant d'effectuer des tests d'exécution.
> 
> Exemple:
> `public static void main(String[] args){ System.out.println("Hello"); }`
> 
> Merci.

Ok!

**Comment by Faraykg** [comment]
Etudiant
Cours
Faculté

**Comment by SergeSULABOSIO** [comment]
Il reste 4 classes à modifier, mais nous pouvons déjà closer cette ISSUE!
